packages:
  - "apps/*"
  - "packages/*"
  - "platform/*"
  - "foundation/*"
  - "domains/*"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
overrides:
  database: link:../../platform/database
