packages:
  - 'apps/*'
  - 'domains/*'
  - 'sdui/*'
  - 'platform/*'
  - 'foundation/*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
