export enum ErrorCode {
  // Authentication & Security
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Customer Garage & Booking
  VEHICLE_NOT_FOUND = 'VEHICLE_NOT_FOUND',
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_INVALID_STATE = 'BOOKING_INVALID_STATE',
  BOOKING_SLOT_UNAVAILABLE = 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_OVERLAPPING = 'BOOKING_OVERLAPPING',

  // Payments, Invoices & Payouts
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_ORDER_CREATION_FAILED = 'PAYMENT_ORDER_CREATION_FAILED',
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  PAYOUT_NOT_ELIGIBLE = 'PAYOUT_NOT_ELIGIBLE',

  // Tracking & Notifications
  TRACKING_SESSION_NOT_FOUND = 'TRACKING_SESSION_NOT_FOUND',
  DEVICE_TOKEN_INVALID = 'DEVICE_TOKEN_INVALID',

  // Reviews & Coupons
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  REVIEW_NOT_ELIGIBLE = 'REVIEW_NOT_ELIGIBLE',
  COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
  COUPON_INACTIVE = 'COUPON_INACTIVE',
  COUPON_EXPIRED = 'COUPON_EXPIRED',
  COUPON_MIN_AMOUNT_NOT_MET = 'COUPON_MIN_AMOUNT_NOT_MET',
  COUPON_USAGE_LIMIT_EXCEEDED = 'COUPON_USAGE_LIMIT_EXCEEDED',
}
