### Test Auth Login Screen
GET http://127.0.0.1:3000/api/v1/screen/auth/auth_login
Accept: application/json

###

### Test Auth OTP Screen
GET http://127.0.0.1:3000/api/v1/screen/auth/auth_otp
Accept: application/json

###



### Test App Init (Config API) - Guest Mode
GET http://127.0.0.1:3000/api/v1/app/init
Accept: application/json

###

### Test App Init (Config API) - Logged In Mode
GET http://127.0.0.1:3000/api/v1/app/init
Accept: application/json
Authorization: Bearer mock-token
